# Generated by Django 5.1.7 on 2025-04-23 19:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(max_length=100)),
                ('commentsNum', models.IntegerField(default=0)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None)),
                ('nutrition', models.JSONField()),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, size=None)),
                ('gallery', models.CharField(blank=True, max_length=200)),
                ('userFK', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_story_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('protein', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('comments', models.IntegerField(default=0)),
                ('userFK', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
